apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30080