apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.appName }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 5000
          env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.appName }}-configmap
                key: APP_NAME
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.appName }}-configmap
                key: VERSION
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.appName }}-configmap
                key: ENVIRONMENT
