apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-prod-sercret-store
  namespace: prod-namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key