{{- if not .Values.secrets_manager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  PASSWORD: {{ .Values.password }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: {{ .Values.appName }}-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: app/password
{{- end }}