apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000