apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  APP_NAME: {{ .Values.appName }}
  ENVIRONMENT: {{ .Values.environment }}
  VERSION: {{ .Values.image.tag }}
  {{ if eq .Values.environment dev }}
  PASSWORD: dummy-password
  {{ end }}