apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  TOKEN: {{ .Values.secret.token }}