name: Init ArgoCD files

on:
  push:
    branches:
      - main
    paths:
      - 'apps/*'

jobs:
  init-argocd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Extract App Names
      run: |
        # Get the list of app directories and format as YAML list
        APP_NAMES=$(ls -1 apps/ | sed 's/^/- /')

        # Create or update global-argocd/values.yaml with the app names
        echo "apps:" > global-argocd-app/values.yaml
        echo "$APP_NAMES" >> global-argocd-app/values.yaml

    - name: Generate Helm Templates
      run: |
        mkdir -p argocd
        mkdir -p argocd/nonprod
        for file in environments/*.yaml; do
          if [ "$file" != "environments/prod-values.yaml" ]; then
            env=$(basename $file .yaml | cut -d'-' -f1)
            output_file="$env-argocd.yaml"
            helm template test --values $file global-argocd-app > argocd/nonprod/$output_file
          fi
        done
        mkdir -p argocd/prod
        helm template test --values environments/prod-values.yaml global-argocd-app > argocd/prod/prod-argocd.yaml

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add global-argocd-app/values.yaml
        git add argocd/
        git commit -m "An application was added or deleted"
        git push

  
